### ISSUE TITLE
Support change to .Net Standard 2.0 in Gjallarhorn

### ISSUE THREAD

**Issue by mtnrbq** [ReedCopsey/Gjallarhorn.Bindable#13]
The change to address ReedCopsey/Gjallarhorn#43 requires corresponding changes in this dependent repository.
@ReedCopsey

**Comment by ReedCopsey** [comment]
This is done, but Android projects are failing on build (at least for me). Still some work to do here.

**Comment by mtnrbq** [comment]
Hmm ok I'll dig into that

**Comment by mtnrbq** [comment]
There seems to be an issue with the ElmInspiredOne.fsproj - hangs on loading in VS2017 15.6

**Comment by ReedCopsey** [comment]
@mtnrbq So - got that loading. It's an issue with new F# project system. Should load properly now, but the main android (C#) project is failing horribly for me.

**Comment by FoggyFinder** [comment]
Sample project builds fine now - there was a contradictory condition in paket files (Main group targets .netstandard while Android project have to have references to platform specific packages as well).

Not a Paket expert so moved to NuGet at least temporarly.
