### ISSUE TITLE
Problem with `ElmInspiredOne` project

### ISSUE THREAD

**Issue by FoggyFinder** [ReedCopsey/Gjallarhorn.Bindable#16]
Seems like there is a missing link to Gjallarhorn package at the [paket.references](https://github.com/ReedCopsey/Gjallarhorn.Bindable/blob/master/samples/ElmInspiredOne/Wpf/paket.references) file

So, it have to be:

```
group WpfSamples
    FSharp.Core
    FsXaml.Wpf
    Gjallarhorn
```

**Comment by ReedCopsey** [comment]
Makes sense. Want to fix? If not, I'll try to update it soon.
