### ISSUE TITLE
Support for AvaloniaUI

### ISSUE THREAD

**Issue by boyedarat** [ReedCopsey/Gjallarhorn.Bindable#19]
Any plans or interest in supporting AvaloniaUI?
Project link: https://github.com/AvaloniaUI/Avalonia

**Comment by ReedCopsey** [comment]
I'm very interested in doing this, but haven't had the time personally to tackle it (yet).

I'd be very open to working with somebody who wanted to put the effort into a PR to make this work, including spending some time mentoring them on what would be required. It should be a fairly straightforward port of the existing code to make an avalonia backend.

**Comment by boyedarat** [comment]
Looks like there is already a pre-release available:
https://www.nuget.org/packages/Gjallarhorn.Bindable.Avalonia/1.0.0-beta7
