### ISSUE TITLE
build.cmd fails from clean 'git clone'

### ISSUE THREAD

**Issue by gdennie** [ReedCopsey/Gjallarhorn.Bindable#6]
Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn
    15>MainActivity.cs(9,49): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
        [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj]
    15>MainActivity.cs(11,33): error CS0115: 'MainActivity.OnCreate(Bundle)': no suitable method found to override [C:\Users\gd\Documents\Gjallarhorn.Bindable\sa
       mples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj]
    15>Done Building Project "C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj"
        (Rebuild target(s)) -- FAILED.
     1>Done Building Project "C:\Users\gd\Documents\Gjallarhorn.Bindable\Gjallarhorn.Bindable.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "C:\Users\gd\Documents\Gjallarhorn.Bindable\Gjallarhorn.Bindable.sln" (Rebuild target) (1) ->
       "C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj" (Rebuild target) (15)
        ->
       (ResolveAssemblyReferences target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Gjallarhorn". Check to make sure the assembly exists on disk. If this reference is required by y
       our code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredO
       neXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.Animated.Vector.Drawable". Check to make sure the assembly exists on dis
       k. If this reference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\
       ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.Design". Check to make sure the assembly exists on disk. If this referen
       ce is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.A
       ndroid\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.v4". Check to make sure the assembly exists on disk. If this reference i
       s required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Andro
       id\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.v7.AppCompat". Check to make sure the assembly exists on disk. If this r
       eference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredO
       neXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.v7.CardView". Check to make sure the assembly exists on disk. If this re
       ference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOn
       eXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.v7.MediaRouter". Check to make sure the assembly exists on disk. If this
        reference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspire
       dOneXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.v7.RecyclerView". Check to make sure the assembly exists on disk. If thi
       s reference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspir
       edOneXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Android.Support.Vector.Drawable". Check to make sure the assembly exists on disk. If thi
       s reference is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspir
       edOneXF.Android\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "FormsViewGroup". Check to make sure the assembly exists on disk. If this reference is required b
       y your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspir
       edOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Forms.Core". Check to make sure the assembly exists on disk. If this reference is requir
       ed by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmIn
       spiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Forms.Platform". Check to make sure the assembly exists on disk. If this reference is re
       quired by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\E
       lmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Forms.Platform.Android". Check to make sure the assembly exists on disk. If this referen
       ce is required by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.A
       ndroid\ElmInspiredOneXF.Android.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could n
       ot resolve this reference. Could not locate the assembly "Xamarin.Forms.Xaml". Check to make sure the assembly exists on disk. If this reference is requir
       ed by your code, you may get compilation errors. [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmIn
       spiredOneXF.Android.csproj]

       "C:\Users\gd\Documents\Gjallarhorn.Bindable\Gjallarhorn.Bindable.sln" (Rebuild target) (1) ->
       "C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj" (Rebuild target) (15)
        ->
       (CoreCompile target) ->
         MainActivity.cs(9,49): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference
       ?) [C:\Users\gd\Documents\Gjallarhorn.Bindable\samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj]
         MainActivity.cs(11,33): error CS0115: 'MainActivity.OnCreate(Bundle)': no suitable method found to override [C:\Users\gd\Documents\Gjallarhorn.Bindable\
       samples\ElmInspiredOne\Xamarin\ElmInspiredOneXF.Android\ElmInspiredOneXF.Android.csproj]

    14 Warning(s)
    2 Error(s)

Time Elapsed 00:00:54.70
Running build failed.
Error:
Building C:\Users\gd\Documents\Gjallarhorn.Bindable\Gjallarhorn.Bindable.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0063960
AssemblyInfo   00:00:00.1145980
Build          Failure
Total:         00:00:57.5485069
---------------------------------------------------------------------
Status:        Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building C:\Users\gd\Documents\Gjallarhorn.Bindable\Gjallarhorn.Bindable.sln failed with exitcode 1.
  2) CS0234: MainActivity.cs(9,49): The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
  3) CS0115: MainActivity.cs(11,33): 'MainActivity.OnCreate(Bundle)': no suitable method found to override
---------------------------------------------------------------------

**Comment by ReedCopsey** [comment]
This looks like you're getting errors compiling the Xamarin projects. Do you have the full Xamarin tools installed for VS 2017?

**Comment by mtnrbq** [comment]
FWIW I just did a git clone, with VS2017 15.5.3 and Xamarin tooling, and build.cmd worked fine 
- even better, deploying from vs2017 to an android device using Vysor resulted in a running app (ElmInspiredOneXF.Android)

**Comment by ReedCopsey** [comment]
Great! Thank you for the update
