### ISSUE TITLE
The function callable by command gets calling twice

### ISSUE THREAD

**Issue by FoggyFinder** [ReedCopsey/Gjallarhorn.Bindable#9]
From Q on SO:

https://stackoverflow.com/questions/47997138/the-function-callable-by-command-get-calling-twice

Simple demo

https://github.com/FoggyFinder/GjlBindableDemo

**Comment by ReedCopsey** [comment]
It appears this happens because the observable is subscribed to in 2 places internally.

**Comment by ReedCopsey** [comment]
Should be fixed in https://www.nuget.org/packages/Gjallarhorn.Bindable/1.0.0-beta6
